/* ---- SITE SETTINGS: change these to rebrand the whole site for any funeral home ----
   (staff can also change them later in Dashboard > Site content) */
var SITE={name:'Your Funeral Home',tagline:'Funeral & Cremation Services',place:'City, Province',phone:'(000) 000-0000',address:'Street, City, Province, Country'};
/* ---- Sample data (stands in for the backend API) ---- */
var OB=[
{id:1,name:'Rosario T. Villanueva',born:'1948-03-04',died:'2025-02-11',bio:'Rosario spent thirty-one years teaching grade school in her hometown before retiring in 2010. She raised four children and is remembered for her garden of orchids.',family:'Survived by her children Elena, Marco, Joy, and Paolo, and eight grandchildren.',inter:'Lawn lot B-12, Memorial Garden',candles:42,
 sched:[['Wake','2025-02-12','9:00 AM','Memorial Chapel'],['Mass','2025-02-15','6:00 PM','St. Michael Parish Church'],['Interment','2025-02-16','8:00 AM','Memorial Garden']],
 cond:[['A former student','Ma\u2019am Rosario taught half the barangay how to read. We will miss her patience and her laugh.'],['A neighbor','Thank you for always welcoming us into your garden, Nanay Ross. Rest well.']]},
{id:2,name:'Emilio R. Dagohoy',born:'1955-09-21',died:'2025-02-12',bio:'Kuya Emil drove a jeepney along the town route for over thirty years and knew every regular passenger by name.',family:'Survived by his wife Lorna and three children.',inter:'Cremation, niche at Memorial Garden',candles:27,
 sched:[['Cremation','2025-02-13','10:00 AM','Crematorium']],cond:[['A neighbor','Kuya Emil always waited for us after the late shift. Salamat sa lahat, Kuya.']]},
{id:3,name:'Teresita M. Alcantara',born:'1939-12-02',died:'2024-11-19',bio:'A devoted seamstress and choir member, Teresita sewed the school uniforms of three generations in her barangay.',family:'Survived by her daughters Gina and Marites, and five grandchildren.',inter:'Lawn lot A-04, Memorial Garden',candles:35,sched:[],cond:[]},
{id:4,name:'Ernesto B. Ramos',born:'1962-06-15',died:'2024-08-03',bio:'Ernesto worked abroad for twenty years so his children could study. He came home in 2020 and spent his last years fishing with his grandsons.',family:'Survived by his wife Cora and two children.',inter:'Cremation service, Crematorium',candles:51,sched:[],cond:[['OFW colleague','Kabayan, thank you for the years in Riyadh. We watched the service from abroad.']]}];
var SERV=[['Cremation Services','Cremation with respectful handling and help with documents. Schedules are confirmed with the family by email.','#/services/cremation'],['Lawn Lot Options','Garden lots in a landscaped memorial park. Families can view availability on the lawn lot map.','#/services/lawn-lot'],['Digital Memorial Page','Every family can have an online obituary with a QR code, a condolence board, and shareable link.','#/obituaries'],
['Flowers','Coming soon. Fresh flower arrangements for the wake, the service, and the interment, prepared with the family.','#/services/flowers',1],
['Cremation Urns','Coming soon. A selection of urns for families who choose cremation.','#/services/urns',1],
['Caskets','Coming soon. Casket options for families planning a burial in the garden.','#/services/caskets',1],
['Live Streaming','Coming soon. Broadcast the wake or the service online so family and friends far away can take part.','#/services/livestream',1]];
/* Arrangements: each one is either a Cremation or a Lawn lot. Status: Scheduled, Pending confirmation, or Draft. */
var SCHED=[
{id:1,name:'Emilio R. Dagohoy',type:'Cremation',date:'2025-02-13',time:'10:00',lot:'',status:'Scheduled'},
{id:2,name:'Teresita M. Alcantara',type:'Lawn lot',date:'2025-02-20',time:'09:00',lot:'A-04',status:'Scheduled'},
{id:3,name:'Ernesto B. Ramos',type:'Cremation',date:'2025-02-24',time:'14:00',lot:'',status:'Pending confirmation'}];
var LOT_STATE={};['A','B','C'].forEach(function(b){for(var i=1;i<=24;i++){var h=(b.charCodeAt(0)*31+i*17)%10;LOT_STATE[b+'-'+(i<10?'0':'')+i]=h<4?'occ':h<6?'res':'avail'}});
var SVC=['General question','Cremation Services','Lawn Lot Options','Digital Memorial Page','Flowers','Cremation Urns','Caskets','Live Streaming','Planning Ahead'];
var INQ=[{id:1,name:'Juan Dela Cruz',email:'juan@email.com',subject:'Arrangement inquiry',service:'Cremation Services',msg:'Good day, I would like to ask about available cremation slots this week.',status:'Unread',at:'Feb 10, 2025',date:'2025-02-10'},{id:2,name:'Marites Alcantara',email:'marites@email.com',subject:'Lawn lot B-12',service:'Lawn Lot Options',msg:'Is lot B-12 still available for reservation?',status:'Read',at:'Feb 8, 2025',date:'2025-02-08'}];
var CONTENT={mission:'To give every family a dignified, caring farewell and a lasting place of remembrance. [Edit with the facility\u2019s mission.]',vision:'A memorial garden where no family has to grieve alone, wherever they are in the world. [Edit with the facility\u2019s vision.]',philosophy:'[Operational philosophy goes here: how the facility handles each family with respect, clear timelines, and open communication.]',phone:SITE.phone,address:SITE.address,hours:'[Operating hours]'};
var ACT=[['Feb 12, 9:15 AM','admin','Published obituary: Emilio R. Dagohoy','2025-02-12'],['Feb 11, 4:40 PM','staff','Emailed the family of Emilio R. Dagohoy the cremation schedule','2025-02-11'],['Feb 10, 10:05 AM','admin','Saved as draft: Ernesto B. Ramos','2025-02-10']];
function logAct(t){ACT.unshift([new Date().toLocaleString('en-US',{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}),session||'Staff',t,iso()])}
var session=null;var state={q:''};
/* Condolence moderation: when on, new messages wait as Pending until staff approve them */
var MOD={on:true};
var LOTSEC='<div class="legend"><span><i style="background:var(--lotA)"></i>Available</span><span><i style="background:var(--lotR)"></i>Reserved</span><span><i style="background:var(--lotO)"></i>Occupied</span></div><div class="two" style="align-items:start" id="lotwrap"></div>';
var CF='<form class="panel" id="cf"><div id="cm"></div><div class="fr"><label for="cn">Your name</label><input id="cn" required></div><div class="fr"><label for="ce">Email</label><input id="ce" type="email" required></div><div class="fr"><label for="csv">Service</label><select id="csv">'+SVC.map(function(s){return '<option>'+s+'</option>'}).join('')+'</select></div><div class="fr"><label for="cs">Subject</label><input id="cs" required></div><div class="fr"><label for="cmg">Message</label><textarea id="cmg" required></textarea></div><button class="btn">Send inquiry</button></form>';
/* ---- helpers ---- */
function esc(s){return String(s==null?'':s).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function fd(s){var d=new Date(s+'T00:00:00');return isNaN(d)?s:d.toLocaleDateString('en-US',{year:'numeric',month:'long',day:'numeric'})}
function ft(t){if(!t)return '';var p=t.split(':'),h=+p[0];return ((h+11)%12+1)+':'+p[1]+' '+(h<12?'AM':'PM')}
function applyBrand(){var g=function(i){return document.getElementById(i)};g('bn').textContent=SITE.name;g('bt').textContent=SITE.tagline+' \u00b7 '+SITE.place;g('fname').textContent='\u00a9 '+new Date().getFullYear()+' '+SITE.name+', '+SITE.place}
function iso(){var d=new Date(),p=function(n){return n<10?'0'+n:''+n};return d.getFullYear()+'-'+p(d.getMonth()+1)+'-'+p(d.getDate())}
function inR(p,d){var a=document.getElementById(p+'_f').value,b=document.getElementById(p+'_t').value;if(!a&&!b)return true;if(!d)return false;return(!a||d>=a)&&(!b||d<=b)}
function dateBar(p,l){return '<div class="dbar"><div><label for="'+p+'_f">'+l+': from</label><input type="date" id="'+p+'_f"></div><div><label for="'+p+'_t">to</label><input type="date" id="'+p+'_t"></div><button class="btn sm ghost" type="button" id="'+p+'_x">Clear dates</button></div>'}
function samp(t,a,b){var v='<svg xmlns="http://www.w3.org/2000/svg" width="600" height="600"><defs><linearGradient id="g" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="'+a+'"/><stop offset="1" stop-color="'+b+'"/></linearGradient></defs><rect width="600" height="600" fill="url(#g)"/><circle cx="300" cy="240" r="90" fill="rgba(255,255,255,.55)"/><path d="M110 560c0-110 85-190 190-190s190 80 190 190z" fill="rgba(255,255,255,.55)"/><text x="300" y="590" text-anchor="middle" font-family="Georgia,serif" font-size="26" fill="rgba(0,0,0,.45)">'+t+'</text></svg>';return 'data:image/svg+xml;utf8,'+encodeURIComponent(v)}
/* each condolence is [name, message, status] where status is Approved, Pending, or Rejected */
OB.forEach(function(o){o.photos=[];o.status='Published';o.cond=o.cond.map(function(c){return [c[0],c[1],'Approved',o.died]})});OB[2].status='Archived';OB[3].status='Draft';
OB[0].cond.push(['A relative','Thinking of you all. Our family is praying for you.','Pending','2025-02-14']);
function getOb(id){var o=OB.filter(function(x){return x.id==id})[0];return o&&(o.status!=='Draft'||session)?o:null}
OB[0].photos=[samp('Sample photo 1','#c9d4bd','#8fa17f'),samp('Sample photo 2','#ead9bb','#c4a373'),samp('Sample photo 3','#d6dfd0','#9ab08c'),samp('Sample photo 4','#efe3c9','#bfa070')];
OB[2].photos=[samp('Sample photo 1','#d8cdb8','#a89672'),samp('Sample photo 2','#cdd8c8','#8ea383')];
function ph(o){return o.photos&&o.photos.length?'<img src="'+o.photos[0]+'" alt="">':esc(ini(o.name))}
function readImgs(files){return Promise.all([].slice.call(files).filter(function(f){return /^image\//.test(f.type)}).map(function(f){return new Promise(function(res){var r=new FileReader();r.onload=function(){var im=new Image();im.onload=function(){var k=Math.min(1,1000/Math.max(im.width,im.height)),c=document.createElement('canvas');c.width=Math.round(im.width*k);c.height=Math.round(im.height*k);c.getContext('2d').drawImage(im,0,0,c.width,c.height);res(c.toDataURL('image/jpeg',.82))};im.onerror=function(){res(null)};im.src=r.result};r.onerror=function(){res(null)};r.readAsDataURL(f)})})).then(function(a){return a.filter(Boolean)})}
function thumbs(el,arr){el.innerHTML=arr.map(function(u,i){return '<div class="thumb"><img src="'+u+'" alt=""><button type="button" data-i="'+i+'" aria-label="Remove photo">\u00d7</button></div>'}).join('');el.onclick=function(e){var b=e.target.closest('button');if(b){arr.splice(b.dataset.i,1);thumbs(el,arr)}}}
function ini(n){return n.split(' ').filter(function(w){return /^[A-Z]/.test(w)}).slice(0,2).map(function(w){return w[0]}).join('')}
function card(o){return '<a class="card" href="#/memorial/'+o.id+'"><div class="cph">'+ph(o)+'</div><div class="cb"><p class="t serif">'+esc(o.name)+'</p><p class="d">'+o.born.slice(0,4)+' – '+o.died.slice(0,4)+'</p></div></a>'}
function head(eb,t,p){return '<section class="hero"><div class="page"><p class="eyebrow">'+eb+'</p><h1>'+t+'</h1><p class="lede" style="margin:0">'+p+'</p></div></section>'}
function aboutCards(){var I={m:'<circle cx="20" cy="20" r="16"/><circle cx="20" cy="20" r="9"/><circle cx="20" cy="20" r="2"/>',v:'<path d="M2 20c6-10 30-10 36 0-6 10-30 10-36 0z"/><circle cx="20" cy="20" r="5"/>',p:'<path d="M8 32C8 14 20 6 34 6c0 16-8 26-24 26z"/><path d="M8 32L24 16"/>'};
return [['m','Mission',CONTENT.mission],['v','Vision',CONTENT.vision],['p','Our philosophy',CONTENT.philosophy]].map(function(x){return '<a class="card" href="#/about"><div class="cph"><svg width="44" height="44" viewBox="0 0 40 40" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">'+I[x[0]]+'</svg></div><div class="cb"><p class="t serif">'+x[1]+'</p><p class="s">'+esc(x[2])+'</p></div></a>'}).join('')}
function moreCards(){var I={flowers:'<circle cx="23" cy="9" r="5"/><circle cx="32" cy="16" r="5"/><circle cx="28" cy="26" r="5"/><circle cx="18" cy="26" r="5"/><circle cx="14" cy="16" r="5"/><circle cx="23" cy="19" r="3"/><path d="M23 30v14"/>',urns:'<path d="M17 6h12M19 6v5c-6 3-9 8-9 15 0 7 5 11 13 11s13-4 13-11c0-7-3-12-9-15V6"/><path d="M12 22h22"/>',caskets:'<path d="M16 4h14l8 12-5 26H13L8 16z"/><path d="M23 14v18M17 20h12"/>',livestream:'<rect x="4" y="13" width="26" height="20" rx="3"/><path d="M30 21l12-6v16l-12-6"/><circle cx="11" cy="20" r="1.5"/>'};
return SERV.slice(3).map(function(x){var k=x[2].split('/').pop();return '<div class="card" id="'+k+'"><div class="cph"><svg width="46" height="46" viewBox="0 0 46 46" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">'+I[k]+'</svg></div><div class="cb"><p class="t serif">'+esc(x[0])+' <span class="pill warn">Coming soon</span></p><p class="s">'+esc(x[1])+'</p></div></div>'}).join('')}
/* ---- pages ---- */
var pages={
home:function(){return '<section class="hero"><div class="page"><p class="eyebrow">Digital obituary &amp; memorial management</p><h1>A place to remember, a way to reach everyone who cared.</h1><p class="lede">Search obituaries, see our services, and leave a condolence for a loved one. Everything in one place, for families and friends near or far.</p><form class="srow" id="hs"><input id="hq" placeholder="Search by name, e.g. Rosario Villanueva" aria-label="Search by name"><button class="btn">Search</button></form></div></section>'
+'<section class="blk"><div class="page"><div class="bh"><div><h2>About us</h2><p>Serving families in '+esc(SITE.place)+' for decades with dignified cremation services and garden lawn lots.</p></div><a class="more" href="#/about">Read more about us</a></div><div class="g3">'+aboutCards()+'</div></div></section>'
+'<section class="blk"><div class="page"><div class="bh"><div><h2>Recently honored</h2><p>Digital obituary profiles, kept searchable for as long as they are needed.</p></div><a class="more" href="#/obituaries">View all obituaries</a></div><div class="g3">'+OB.filter(function(o){return o.status==='Published'}).slice(0,3).map(card).join('')+'</div></div></section>'
+'<section class="blk"><div class="page"><div class="bh"><div><h2>Our services</h2><p>Cremation, lawn lots, and more options on the way.</p></div><a class="more" href="#/services">View services</a></div><div class="g3">'+SERV.map(function(s){return '<a class="card" href="'+(s[2]||'#/services')+'"><div class="cb"><p class="t serif">'+s[0]+(s[3]?' <span class="pill warn">Coming soon</span>':'')+'</p><p class="s">'+s[1]+'</p></div></a>'}).join('')+'</div></div></section>'
+'<section class="blk" id="contact-home"><div class="page two" style="align-items:start"><div><h2 class="serif" style="font-size:26px;margin-bottom:8px">Contact us</h2><p style="color:var(--soft);max-width:44ch">Send an inquiry and it goes straight to the management\u2019s inbox. For privacy, cremation schedules are not posted publicly. Our staff confirms them with the family by email.</p><div class="row" style="margin-top:14px"><span>Phone</span><span>'+esc(CONTENT.phone)+'</span></div><div class="row"><span>Address</span><span>'+esc(CONTENT.address)+'</span></div></div>'+CF+'</div></section>'},
about:function(){return head('About Us','Serving families in '+esc(SITE.place),esc(SITE.name)+' has served families for decades, offering dignified cremation services and garden lawn lots.')
+'<section class="blk"><div class="page two"><div class="panel"><h3 class="serif">Mission</h3><p style="color:var(--soft)">'+esc(CONTENT.mission)+'</p></div><div class="panel"><h3 class="serif">Vision</h3><p style="color:var(--soft)">'+esc(CONTENT.vision)+'</p></div></div></section>'
+'<section class="blk"><div class="page"><div class="panel"><h3 class="serif" style="margin-bottom:8px">Our philosophy</h3><p style="color:var(--soft);max-width:60ch">'+esc(CONTENT.philosophy)+'</p><div class="row"><span>Address</span><span>'+esc(CONTENT.address)+'</span></div><div class="row"><span>Contact</span><span>'+esc(CONTENT.phone)+'</span></div><div class="row"><span>Hours</span><span>'+esc(CONTENT.hours)+'</span></div></div></div></section>'
+'<section class="blk"><div class="page"><h2 class="serif" style="font-size:26px;margin-bottom:8px">Our services</h2><p style="color:var(--soft);max-width:56ch">We offer cremation services and lawn lot options.</p><a class="btn" href="#/services">See all services</a></div></section>'},
obituaries:function(){return head('Obituaries','Search past obituaries','Filter by name, birth date, or death date. Useful for relatives and OFWs looking for a record.')
+'<section class="blk"><div class="page"><form class="filters" id="of"><div><label for="fq">Name</label><input id="fq" value="'+esc(state.q||'')+'"></div><div><label for="fb">Born on or after</label><input id="fb" type="date"></div><div><label for="fdd">Died on or before</label><input id="fdd" type="date"></div><button class="btn">Search</button></form><div class="g3" id="ol"></div></div></section>'},
services:function(){return head('Services','Cremation services and lawn lot options','What the facility offers, explained. The details below are sample wording; replace the bracketed parts with the facility\u2019s own information.')
+'<section class="blk"><div class="page"><div class="share"><a class="btn sm ghost" href="#/services/cremation">Cremation services</a><a class="btn sm ghost" href="#/services/lawn-lot">Lawn lot options</a><a class="btn sm ghost" href="#/services/flowers">Flowers</a><a class="btn sm ghost" href="#/services/urns">Urns</a><a class="btn sm ghost" href="#/services/caskets">Caskets</a><a class="btn sm ghost" href="#/services/livestream">Live streaming</a></div></div></section>'
+'<section class="blk" id="cremation"><div class="page"><div class="bh"><div><h2>Cremation services</h2><p>A dignified cremation handled with care, with clear communication at every step. For privacy, schedules are never posted publicly. Our staff confirms the date and time with the family by email.</p></div></div>'
+'<div class="two" style="align-items:start"><div class="panel"><h3 class="serif" style="margin-bottom:8px">What is included</h3><div class="row"><span>Receiving and respectful handling of the deceased</span></div><div class="row"><span>Help with the required documents</span></div><div class="row"><span>Scheduled cremation at the facility\u2019s crematorium</span></div><div class="row"><span>Release of the remains to the family in an urn</span></div><div class="row"><span>[Other inclusions, such as chapel use or urn options]</span></div></div>'
+'<div class="panel"><h3 class="serif" style="margin-bottom:8px">How it works</h3><ol class="steps"><li>Contact us with the name of the deceased and a preferred date.</li><li>Our staff reviews the documents and confirms availability.</li><li>The family receives the schedule by email.</li><li>The cremation is carried out at the scheduled time.</li><li>The remains are released to the family, or placed in a niche or lawn lot.</li></ol></div></div>'
+'<p style="margin-top:20px"><a class="btn" href="#/contact">Ask about cremation</a></p></div></section>'
+'<section class="blk" id="lawn-lot"><div class="page"><div class="bh"><div><h2>Lawn lot options</h2><p>A lawn lot is a burial plot in a landscaped memorial garden, kept open and green so families have a quiet place to visit.</p></div></div>'
+'<div class="two" style="align-items:start"><div class="panel"><h3 class="serif" style="margin-bottom:8px">Choosing a lot</h3><div class="row"><span>Single lot</span><span>[Size and price]</span></div><div class="row"><span>Family lot</span><span>[Size and price]</span></div><div class="row"><span>Payment terms</span><span>[Details]</span></div><div class="row"><span>Garden care</span><span>[What upkeep is included]</span></div></div>'
+'<div class="panel"><h3 class="serif" style="margin-bottom:8px">How to reserve</h3><ol class="steps"><li>Open the lawn lot map and look for an available lot.</li><li>Send us an inquiry with the lot number you prefer.</li><li>Our staff confirms it and explains the requirements.</li><li>Once reserved, the lot shows as reserved on the map.</li></ol><p style="color:var(--faint);font-size:13px;margin:12px 0 0">On the map, a lot is available, reserved, or occupied.</p></div></div>'
+'<p style="margin-top:20px;display:flex;gap:10px;flex-wrap:wrap"><a class="btn" href="#/lots">View the lawn lot map</a><a class="btn ghost" href="#/contact">Ask about a lot</a></p></div></section>'
+'<section class="blk" id="more-options"><div class="page"><div class="bh"><div><h2>More options, coming soon</h2><p>We are preparing these additions for families. Send us an inquiry if you would like to be told when they are ready.</p></div></div><div class="g3">'+moreCards()+'</div><p style="margin-top:20px"><a class="btn" href="#/contact">Ask to be notified</a></p></div></section>'},
planning:function(){var lv='';for(var i=0;i<12;i++)lv+='<path transform="rotate('+(i*30)+' 130 130)" d="M130 34c11 9 11 23 0 33-11-10-11-24 0-33z"/>';
return '<section class="hero plan"><div class="page two" style="align-items:center"><div><p class="eyebrow">Planning ahead</p><h1>Make the hard decisions now, so your family doesn\u2019t have to.</h1><p class="lede">A plan made in calm days is a gift to the people you love. Tell us how you wish to be remembered and we will keep it on record, with no pressure and no obligation.</p><p style="display:flex;gap:10px;flex-wrap:wrap;margin:0"><button class="btn" type="button" id="pgo">Start my plan</button><a class="btn ghost" href="#/services">See our services</a></p></div><div class="plan-art" aria-hidden="true"><svg viewBox="0 0 260 260" width="260" height="260" fill="none"><circle cx="130" cy="130" r="112" stroke="var(--gold)" stroke-width="1.2" stroke-dasharray="2 6"/><g fill="var(--pale)" stroke="var(--sage)" stroke-width="1.4">'+lv+'</g><path d="M130 82c14 14 21 24 14 35-3 5-25 5-28 0-7-11 0-21 14-35z" fill="var(--gold)"/><path d="M130 98c5 6 7 10 4 14-1.500 2.500-6.500 2.500-8 0-3-4-1-8 4-14z" fill="var(--surface)"/><path d="M130 124v10" stroke="var(--ink)" stroke-width="3" stroke-linecap="round"/><rect x="108" y="134" width="44" height="40" rx="4" stroke="var(--sage)" stroke-width="3"/><path d="M96 180h68" stroke="var(--sage)" stroke-width="3" stroke-linecap="round"/></svg></div></div></section>'
+'<section class="blk"><div class="page"><div class="bh"><div><h2>Why plan ahead</h2><p>Pre-arranging is a practical act of care. Here is what families tell us it gives them.</p></div></div><div class="g3">'+[['Peace of mind','Know that your wishes are recorded and understood, whatever the future holds.'],['Less burden on family','Spare your loved ones from rushed decisions and costs at a painful time.'],['Your wishes, honored','Choose cremation or a garden lawn lot, and how you would like to be remembered.']].map(function(x){return '<div class="card gb"><div class="cb"><p class="t serif">'+x[0]+'</p><p class="s">'+x[1]+'</p></div></div>'}).join('')+'</div></div></section>'
+'<section class="blk"><div class="page"><div class="bh"><div><h2>How planning ahead works</h2><p>Four simple steps, at your own pace.</p></div></div><div class="tl">'+[['Talk with us','Reach out by form or phone. A staff member listens first.'],['Choose your wishes','Cremation or a lawn lot, with flowers, urns, and caskets as they become available.'],['Put it on record','We note your choices and the family member who should be contacted.'],['Revisit any time','Review or change your plan whenever your wishes change.']].map(function(x,i){return '<div><div class="n">'+(i+1)+'</div><h3 class="serif" style="font-size:17px;margin-bottom:4px">'+x[0]+'</h3><p style="color:var(--soft);font-size:14px;margin:0">'+x[1]+'</p></div>'}).join('')+'</div></div></section>'
+'<section class="blk"><div class="page two" style="align-items:start"><div class="panel"><h3 class="serif" style="margin-bottom:4px">Your planning checklist</h3><p id="pcn" style="color:var(--faint);font-size:13px;margin:0 0 14px"></p><div id="pcl">'+['Cremation or a lawn lot','Where and when the farewell should be held','Flowers (coming soon)','An urn or casket (coming soon)','Important documents in one place','A family member we should contact'].map(function(t,i){return '<label class="chk" for="pc'+i+'"><input type="checkbox" id="pc'+i+'"> '+t+'</label>'}).join('')+'</div><p style="color:var(--faint);font-size:12.5px;margin:6px 0 0">This checklist is only for you. Nothing is saved or sent.</p></div>'
+'<form class="panel" id="plan-form"><h3 class="serif" style="margin-bottom:4px">Request a planning conversation</h3><p style="color:var(--faint);font-size:13px;margin:0 0 14px">Tell us a little and our staff will reach out by email. No payment and no commitment.</p><div id="pm"></div><div class="fr"><label for="pn">Your name</label><input id="pn" required></div><div class="fr"><label for="pe">Email</label><input id="pe" type="email" required></div><div class="fr"><label for="pa">What are you thinking about?</label><select id="pa"><option>Cremation</option><option>Lawn lot</option><option>Not sure yet</option></select></div><div class="fr"><label for="pg">Anything you would like us to know (optional)</label><textarea id="pg"></textarea></div><button class="btn">Send request</button></form></div></section>'
+'<section class="plan-band"><div class="page"><p class="serif" style="font-size:clamp(20px,3vw,28px);font-style:italic;max-width:30ch;margin:0 auto 10px">\u201CA plan made with love is a kindness that lasts.\u201D</p><p style="margin:0;color:#d9d2e0;font-size:14px">'+esc(SITE.name)+'</p></div></section>'},
lots:function(){return head('Lawn Lot Map','See which lots are available','Select a lot to see its status. This is a sample layout, to be replaced with the real garden plan.')
+'<section class="blk"><div class="page">'+LOTSEC+'</div></section>'},
contact:function(){return head('Contact','Send us an inquiry','Your message goes straight to the management\u2019s inbox.')+'<section class="blk"><div class="page" style="max-width:640px">'+CF+'</div></section>'},
login:function(){return '<section class="blk"><div class="page" style="max-width:420px"><form class="panel" id="lf"><h2 class="serif" style="margin-bottom:6px">Staff sign in</h2><p style="color:var(--faint);font-size:13px;margin:0 0 16px">Demo only: use any username with password <b>admin</b>.</p><div id="lm"></div><div class="fr"><label for="lu">Username</label><input id="lu" required></div><div class="fr"><label for="lp">Password</label><input id="lp" type="password" required></div><button class="btn">Sign in</button></form></div></section>'},
admin:function(){if(!session){location.hash='#/login';return ''}
return head('Administrator dashboard','Welcome, '+esc(session),'Only signed-in staff see this page. Public visitors never need an account.')
+'<section class="blk"><div class="page"><div class="tabs" role="tablist" id="tabs"><button class="tab on" type="button" role="tab" data-tab="overview">Overview</button><button class="tab" type="button" role="tab" data-tab="obits">Obituaries</button><button class="tab" type="button" role="tab" data-tab="sched">Cremation schedule</button><button class="tab" type="button" role="tab" data-tab="cond">Condolences</button><button class="tab" type="button" role="tab" data-tab="inq">Inquiries</button><button class="tab" type="button" role="tab" data-tab="site">Site content</button><button class="tab" type="button" role="tab" data-tab="log">Activity log</button></div><div class="tp on" data-t="overview"><div class="g3" style="margin-bottom:28px"><div class="panel"><div class="stat" id="s1"></div>Obituaries</div><div class="panel"><div class="stat" id="s2"></div>Condolences</div><div class="panel"><div class="stat" id="s3"></div>Candles lit</div></div><h3 class="serif" style="margin:28px 0 12px">What staff can do</h3><div class="g3" id="cards"><button class="card" type="button" data-go="obits"><div class="cb"><p class="t serif">Obituaries</p><p class="s">Add, edit, publish, draft, archive, or delete records, and manage photos.</p></div></button><button class="card" type="button" data-go="sched"><div class="cb"><p class="t serif">Cremation schedule</p><p class="s">Set each arrangement as cremation or lawn lot, save drafts, and email families.</p></div></button><button class="card" type="button" data-go="cond"><div class="cb"><p class="t serif">Condolences</p><p class="s">Approve, reject, or remove messages before they appear on memorial pages.</p></div></button><button class="card" type="button" data-go="inq"><div class="cb"><p class="t serif">Inquiries</p><p class="s">Read messages from families, filter by service, and track replies.</p></div></button><button class="card" type="button" data-go="site"><div class="cb"><p class="t serif">Site content</p><p class="s">Edit the About Us details and the services text.</p></div></button><button class="card" type="button" data-go="log"><div class="cb"><p class="t serif">Activity log</p><p class="s">See who changed what, and when.</p></div></button></div><div class="panel" style="margin-top:28px"><h3 class="serif" style="margin-bottom:8px">Recent activity</h3><div id="ra"></div></div></div>'
+'<div class="tp" data-t="obits">'
+'<div class="panel" style="margin-bottom:28px"><h3 class="serif" style="margin-bottom:4px">All deceased</h3><p id="lsum" style="color:var(--faint);font-size:13px;margin:0 0 12px"></p><div class="filters" style="grid-template-columns:2fr 1fr"><div><label for="lq">Search by name</label><input id="lq"></div><div><label for="lsf">Status</label><select id="lsf"><option value="">All</option><option>Published</option><option>Draft</option><option>Archived</option></select></div></div>'+dateBar('ob','Date of death')+'<div class="scroll"><table class="tbl"><thead><tr><th>Name</th><th>Date of death</th><th>Arrangement</th><th>Photos</th><th>Status</th><th></th></tr></thead><tbody id="ltb"></tbody></table></div><p style="color:var(--faint);font-size:13px;margin:12px 0 0">Draft is hidden from the public. Published is visible everywhere. Archived stays searchable but is not shown as recent.</p></div>'
+'<div class="panel" style="margin-bottom:28px"><h3 class="serif" style="margin-bottom:4px">Obituary photos</h3><p style="color:var(--faint);font-size:13px;margin:0 0 12px">Add or remove photos for an existing obituary. The first photo is the main portrait.</p><div class="two"><div class="fr"><label for="mo">Obituary</label><select id="mo"></select></div><div class="fr"><label for="mp">Add photos (you can select several)</label><input id="mp" type="file" accept="image/*" multiple></div></div><div class="thumbs" id="mt"></div></div>'
+'<form class="panel" id="af"><h3 class="serif" id="aht" style="margin-bottom:14px">Add an obituary</h3><div id="am"></div><div class="two"><div class="fr"><label for="an">Full name</label><input id="an" required></div><div class="fr"><label for="ai">Interment details</label><input id="ai"></div><div class="fr"><label for="ab">Date of birth</label><input id="ab" type="date" required></div><div class="fr"><label for="ad">Date of death</label><input id="ad" type="date" required></div></div><div class="fr"><label for="afm">Family details</label><input id="afm"></div><div class="fr"><label for="ap">Photos (select several; the first is the main portrait)</label><input id="ap" type="file" accept="image/*" multiple><div class="thumbs" id="at" style="margin-top:10px"></div></div><div class="fr"><label for="abio">Biography</label><textarea id="abio"></textarea></div><div class="share"><button class="btn" type="button" id="bpub">Publish</button><button class="btn ghost" type="button" id="bdr">Save as draft</button><button class="btn ghost" type="button" id="bpv">Preview</button><button class="btn ghost" type="button" id="bcx">Cancel</button></div><div id="apv"></div></form></div>'
+'</div><div class="tp" data-t="sched">'
+'<div class="panel" style="margin-bottom:28px"><h3 class="serif" style="margin-bottom:4px">Cremation schedule</h3><p style="color:var(--faint);font-size:13px;margin:0 0 8px">Private. Only signed-in staff can see this. Each arrangement is either a cremation or a lawn lot. Families are notified by email.</p>'+dateBar('sc','Arrangement date')+'<div id="sl"></div><div id="em"></div></div>'
+'<form class="panel" id="rf" novalidate><h3 class="serif" id="rht" style="margin-bottom:14px">Add an arrangement</h3><div id="rm"></div><div class="two"><div class="fr"><label for="rn">Name of the deceased</label><input id="rn" list="rnl" autocomplete="off"><datalist id="rnl"></datalist></div><div class="fr"><label for="rt">Arrangement</label><select id="rt"><option>Cremation</option><option>Lawn lot</option></select></div><div class="fr" id="lotf" style="display:none"><label for="rl">Lawn lot (available lots only)</label><select id="rl"></select></div><div class="fr"><label for="rd">Date</label><input id="rd" type="date"></div><div class="fr"><label for="rtm">Time</label><input id="rtm" type="time"></div></div><div class="share"><button class="btn" type="submit">Save arrangement</button><button class="btn ghost" type="button" id="rdr">Save as draft</button><button class="btn ghost" type="button" id="rpb">Preview</button><button class="btn ghost" type="button" id="rcx">Cancel</button></div><div id="rpv"></div></form>'
+'</div><div class="tp" data-t="cond"><div class="panel"><h3 class="serif" style="margin-bottom:4px">Condolences</h3><p style="color:var(--faint);font-size:13px;margin:0 0 14px">Messages visitors left on memorial pages. Only approved messages are shown to the public.</p><label class="chk" for="mod"><input type="checkbox" id="mod"> Review messages before they appear (new messages wait as Pending)</label><div class="filters" style="grid-template-columns:1fr;max-width:260px;margin-bottom:12px"><div><label for="cfs">Show</label><select id="cfs"><option value="">All</option><option>Pending</option><option>Approved</option><option>Rejected</option></select></div></div>'+dateBar('cn','Date posted')+'<div id="cdl"></div></div></div><div class="tp" data-t="inq"><div class="panel"><h3 class="serif" style="margin-bottom:4px">Inquiries</h3><p style="color:var(--faint);font-size:13px;margin:0 0 14px">Messages sent through the contact form.</p><div class="filters" style="grid-template-columns:1fr 1fr;margin-bottom:8px"><div><label for="ifs">Filter by service</label><select id="ifs"></select></div><div><label for="ist">Status</label><select id="ist"><option value="">All</option><option>Unread</option><option>Read</option><option>Replied</option></select></div></div>'+dateBar('iq','Date received')+'<div id="inl"></div></div></div><div class="tp" data-t="site"><form class="panel" id="sf"><h3 class="serif" style="margin-bottom:4px">Site content</h3><p style="color:var(--faint);font-size:13px;margin:0 0 8px">Changes appear on the public Home, About Us, and Services pages.</p><div id="sm2"></div><div class="two"><div class="fr"><label for="c_nm">Funeral home name</label><input id="c_nm"></div><div class="fr"><label for="c_tg">Tagline</label><input id="c_tg"></div></div><div class="fr"><label for="c_pl">City / location</label><input id="c_pl"></div><div class="fr"><label for="c_m">Mission</label><textarea id="c_m"></textarea></div><div class="fr"><label for="c_v">Vision</label><textarea id="c_v"></textarea></div><div class="fr"><label for="c_p">Operating philosophy</label><textarea id="c_p"></textarea></div><div class="two"><div class="fr"><label for="c_ph">Phone</label><input id="c_ph"></div><div class="fr"><label for="c_ad">Address</label><input id="c_ad"></div></div><div class="fr"><label for="c_hr">Operating hours</label><input id="c_hr"></div><h3 class="serif" style="margin:18px 0 8px">Services text</h3><div id="svl"></div><button class="btn" type="submit">Save changes</button></form></div><div class="tp" data-t="log"><div class="panel"><h3 class="serif" style="margin-bottom:4px">Activity log</h3><p style="color:var(--faint);font-size:13px;margin:0 0 8px">Staff actions, newest first.</p>'+dateBar('lg','Date of action')+'<div id="alg"></div></div></div></div></section>'},
memorial:function(id){var o=getOb(id);if(!o)return '<div class="empty">This memorial page could not be found.</div>';
return '<section class="mh"><div class="page mhi"><div class="ph">'+ph(o)+'</div><div><h1 class="serif">'+esc(o.name)+'</h1><div class="dt">'+fd(o.born)+' — '+fd(o.died)+'</div></div></div></section>'
+'<div class="page mb"><div><div class="ms"><h2 class="serif">Life story</h2><p>'+esc(o.bio)+'</p></div><div class="ms"><h2 class="serif">Photos</h2>'+(o.photos.length?'<div class="gal" id="gal">'+o.photos.map(function(u,i){return '<img src="'+u+'" alt="Photo '+(i+1)+' of '+esc(o.name)+'" data-i="'+i+'">'}).join('')+'</div><dialog id="lb"><img alt=""></dialog>':'<div class="panel empty" style="padding:28px">No photos have been added yet.</div>')+'</div>'+'<div class="ms"><h2 class="serif">Family</h2><p>'+esc(o.family)+'</p></div><div class="ms"><h2 class="serif">Interment</h2><p>'+esc(o.inter)+'</p>'
+(o.sched.filter(function(s){return s[0]!=='Cremation'}).length?o.sched.filter(function(s){return s[0]!=='Cremation'}).map(function(s){return '<div class="row"><span>'+s[0]+'</span><span>'+fd(s[1])+' · '+s[2]+' · '+esc(s[3])+'</span></div>'}).join(''):'')+'</div>'
+'<div class="ms"><h2 class="serif">Condolence board</h2><div class="panel"><div id="cl"></div><form id="cdf" style="margin-top:16px"><div id="cdm"></div><div class="fr"><label for="cdn">Name or alias (leave blank to post anonymously)</label><input id="cdn" maxlength="60"></div><div class="fr"><label for="cdt">Your message</label><textarea id="cdt" required></textarea></div><p id="cdnote" style="font-size:12.5px;color:var(--faint);margin:0 0 12px"></p><button class="btn">Post condolence</button></form></div></div></div>'
+'<aside><div class="ms"><h2 class="serif">Light a candle</h2><div class="candle" id="cd"><button class="btn ghost" id="cb" type="button"><svg class="flame" viewBox="0 0 24 32" fill="currentColor" aria-hidden="true"><path d="M12 1c6 7 9 12 6 18-1.500 3-10.500 3-12 0C3 13 6 8 12 1z"/></svg><span id="cbt">Light a candle</span></button><span id="cc" style="color:var(--soft);font-size:14px"></span></div></div>'
+'<div class="ms"><h2 class="serif">Share</h2><div class="share" id="sh"></div></div><div class="ms"><h2 class="serif">QR code</h2><p style="font-size:14px">Families can print or save this code to share offline.</p><div class="qrcard"><div id="qr"></div><div class="qbrand"><svg width="34" height="40" viewBox="0 0 34 40" fill="none" aria-hidden="true"><path d="M17 2c5 5 7.500 8.500 5 12.500-1.200 2-8.800 2-10 0C9.500 10.500 12 7 17 2z" fill="#A8854F"/><path d="M17 8c2 2.500 2.500 4 1.500 5.500-.6.900-2.400.900-3 0C14.500 12 15 10.500 17 8z" fill="#fff"/><path d="M17 16v4" stroke="#26222B" stroke-width="1.6" stroke-linecap="round"/><rect x="9" y="20" width="16" height="16" rx="2" stroke="#6B5B7B" stroke-width="1.8"/><path d="M5 37h24" stroke="#6B5B7B" stroke-width="1.8" stroke-linecap="round"/></svg><p class="qn">'+esc(SITE.name)+'</p><p class="qs">'+esc(SITE.tagline+' \u00b7 '+SITE.place)+'</p><p class="qm">In loving memory of '+esc(o.name)+'</p></div></div><p style="margin-top:10px"><button class="btn sm ghost" id="qd" type="button">Download QR image</button></p></div></aside></div>'}
};

/* ---- page behaviors ---- */
function renderOL(){var q=document.getElementById('fq').value.trim().toLowerCase(),b=document.getElementById('fb').value,d=document.getElementById('fdd').value;
var r=OB.filter(function(o){return o.status!=='Draft'&&(!q||o.name.toLowerCase().indexOf(q)>-1)&&(!b||o.born>=b)&&(!d||o.died<=d)});
document.getElementById('ol').innerHTML=r.length?r.map(card).join(''):'<div class="empty" style="grid-column:1/-1">No obituaries match your search.</div>'}
var after={
home:function(){after.contact();document.getElementById('hs').onsubmit=function(e){e.preventDefault();state.q=document.getElementById('hq').value.trim();location.hash='#/obituaries'}},
obituaries:function(){var f=document.getElementById('of');f.onsubmit=function(e){e.preventDefault();renderOL()};renderOL();state.q=''},
planning:function(){var $=function(i){return document.getElementById(i)};
$('pgo').onclick=function(){$('plan-form').scrollIntoView({behavior:'smooth'})};
var bx=document.querySelectorAll('#pcl input'),upd=function(){var n=0;bx.forEach(function(b){if(b.checked)n++});$('pcn').textContent=n+' of '+bx.length+' considered'};bx.forEach(function(b){b.onchange=upd});upd();
$('plan-form').onsubmit=function(e){e.preventDefault();INQ.unshift({id:Date.now(),name:$('pn').value.trim(),email:$('pe').value.trim(),subject:'Planning ahead: '+$('pa').value,service:'Planning Ahead',msg:$('pg').value.trim()||'(No message)',status:'Unread',at:'Just now',date:iso()});$('pm').innerHTML='<div class="msg">Thank you. Your request was sent to our staff. (Demo: no email is actually sent.)</div>';e.target.reset()}},
lots:function(){var w=document.getElementById('lotwrap'),h='<div>';['A','B','C'].forEach(function(b){h+='<h3 class="serif" style="margin:12px 0 8px">Block '+b+'</h3><div class="lots" style="grid-template-columns:repeat(8,1fr)">';for(var i=1;i<=24;i++){var k=b+'-'+(i<10?'0':'')+i,s=LOT_STATE[k];h+='<button class="lot '+s+'" data-k="'+k+'" aria-label="Lot '+k+', '+s+'">'+i+'</button>'}h+='</div>'});
w.innerHTML=h+'</div><div class="panel" id="li"><h3 class="serif">Lot details</h3><p style="color:var(--soft)">Select a lot on the map.</p></div>';
var nm={avail:'Available',res:'Reserved',occ:'Occupied'};
w.onclick=function(e){var t=e.target.closest('.lot');if(!t)return;w.querySelectorAll('.sel').forEach(function(x){x.classList.remove('sel')});t.classList.add('sel');var k=t.dataset.k;
document.getElementById('li').innerHTML='<h3 class="serif">Lot '+k+'</h3><p><span class="pill">'+nm[LOT_STATE[k]]+'</span></p>'+(LOT_STATE[k]=='avail'?'<a class="btn sm" href="#/contact">Inquire about this lot</a>':'<p style="color:var(--soft)">This lot is not open for new arrangements.</p>')}},
contact:function(){document.getElementById('cf').onsubmit=function(e){e.preventDefault();INQ.unshift({id:Date.now(),name:document.getElementById('cn').value.trim(),email:document.getElementById('ce').value.trim(),subject:document.getElementById('cs').value.trim(),service:document.getElementById('csv').value,msg:document.getElementById('cmg').value.trim(),status:'Unread',at:'Just now',date:iso()});document.getElementById('cm').innerHTML='<div class="msg">Thank you. Your inquiry was sent to our management inbox. (Demo: no email is actually sent.)</div>';e.target.reset()}},
login:function(){document.getElementById('lf').onsubmit=function(e){e.preventDefault();if(document.getElementById('lp').value==='admin'){session=document.getElementById('lu').value.trim();location.hash='#/admin'}else document.getElementById('lm').innerHTML='<div class="msg err">Incorrect username or password.</div>'}},
admin:function(){var $=function(i){return document.getElementById(i)};
/* ---- Cremation schedule: cremation or lawn lot arrangements ---- */
var sl=$('sl'),rf=$('rf'),rm=$('rm'),rpv=$('rpv'),rht=$('rht'),rEdit=null;
var fillNames=function(){$('rnl').innerHTML=OB.map(function(o){return '<option value="'+esc(o.name)+'">'}).join('')};
var fillLots=function(keep){var h='<option value="">Choose a lot</option>';Object.keys(LOT_STATE).forEach(function(k){if(LOT_STATE[k]==='avail'||k===keep)h+='<option>'+k+'</option>'});$('rl').innerHTML=h};
var tog=function(){$('lotf').style.display=$('rt').value==='Lawn lot'?'':'none'};
var rS=function(){var rr=SCHED.filter(function(x){return inR('sc',x.date)});sl.innerHTML=rr.length?rr.map(function(x){return '<div class="row" style="align-items:center"><span style="max-width:22rem"><b>'+esc(x.name)+'</b><br><span style="color:var(--faint);font-size:12.5px">'+(x.type==='Lawn lot'?'Lawn lot'+(x.lot?' '+esc(x.lot):''):'Cremation')+'</span></span><span>'+(x.date?fd(x.date):'No date yet')+(x.time?' · '+ft(x.time):'')+'</span><span style="display:flex;gap:8px;align-items:center;flex-wrap:wrap"><span class="pill'+(x.status==='Scheduled'?'':' warn')+'">'+esc(x.status)+'</span>'+(x.status==='Draft'?'':'<button class="btn sm ghost" type="button" data-act="mail" data-id="'+x.id+'">Email family</button>')+'<button class="btn sm ghost" type="button" data-act="edit" data-id="'+x.id+'">Edit</button><button class="btn sm ghost" type="button" data-act="del" data-id="'+x.id+'">Delete</button></span></div>'}).join(''):'<div class="empty">'+(SCHED.length?'No arrangements in this date range.':'No arrangements yet.')+'</div>'};
var rreset=function(){rf.reset();rEdit=null;tog();fillLots();rht.textContent='Add an arrangement';rpv.innerHTML=''};
var releaseLot=function(x){if(x&&x.lot&&x.status!=='Draft'&&LOT_STATE[x.lot]==='res')LOT_STATE[x.lot]='avail'};
var rsave=function(st){var n=$('rn').value.trim(),t=$('rt').value,lot=t==='Lawn lot'?$('rl').value:'',d=$('rd').value,tm=$('rtm').value;
var err=!n?'Enter the name of the deceased.':st==='Draft'?'':(t==='Lawn lot'&&!lot)?'Choose an available lot for this arrangement.':!d?'Choose a date.':(t==='Cremation'&&!tm)?'Choose a time for the cremation.':'';
if(err){rm.innerHTML='<div class="msg err">'+err+'</div>';return}
var f={name:n,type:t,lot:lot,date:d,time:tm,status:st},x,was=!!rEdit;
if(rEdit){x=SCHED.filter(function(s){return s.id==rEdit})[0];releaseLot(x);for(var k in f)x[k]=f[k]}else{f.id=SCHED.reduce(function(m,s){return Math.max(m,s.id)},0)+1;x=f;SCHED.unshift(x)}
if(st==='Scheduled'&&lot&&LOT_STATE[lot]==='avail')LOT_STATE[lot]='res';
logAct((st==='Draft'?'Saved arrangement as draft':'Saved '+t.toLowerCase()+' arrangement')+': '+n+(was?' (edited)':''));
rreset();rm.innerHTML='<div class="msg">'+(st==='Draft'?'Saved as a draft. It stays private until you save it as an arrangement.':'Arrangement saved.')+'</div>';rS()};
sl.onclick=function(e){var b=e.target.closest('button[data-act]');if(!b)return;var x=SCHED.filter(function(s){return s.id==b.dataset.id})[0];if(!x)return;
if(b.dataset.act==='mail'){logAct('Emailed the family of '+x.name+' the '+x.type.toLowerCase()+' arrangement');b.textContent='Email sent';b.disabled=true;$('em').innerHTML='<div class="msg" style="margin-top:12px">Demo: an email with the '+esc(x.type.toLowerCase())+' details for '+esc(x.name)+' would be sent to the family\u2019s email on file.</div>'}
else if(b.dataset.act==='edit'){rEdit=x.id;$('rn').value=x.name;$('rt').value=x.type;fillLots(x.lot);$('rl').value=x.lot;$('rd').value=x.date;$('rtm').value=x.time;tog();rht.textContent='Edit arrangement: '+x.name;rpv.innerHTML='';rm.innerHTML='<div class="msg">Editing. Choose Save arrangement or Save as draft to keep your changes, or Cancel to leave this one as it was.</div>';rf.scrollIntoView()}
else if(b.dataset.act==='del'){if(b.dataset.arm){releaseLot(x);logAct('Deleted arrangement: '+x.name);SCHED.splice(SCHED.indexOf(x),1);if(rEdit==x.id)rreset();fillLots();rS()}else{b.dataset.arm='1';b.textContent='Confirm delete';setTimeout(function(){if(b.isConnected){b.dataset.arm='';b.textContent='Delete'}},4000)}}};
$('rt').onchange=tog;
rf.onsubmit=function(e){e.preventDefault();rsave('Scheduled')};
$('rdr').onclick=function(){rsave('Draft')};
$('rcx').onclick=function(){var had=rEdit||$('rn').value.trim()||$('rd').value||$('rtm').value;rreset();rm.innerHTML=had?'<div class="msg">Cancelled. Nothing was saved.</div>':''};
$('rpb').onclick=function(){var n=$('rn').value.trim();if(!n){rm.innerHTML='<div class="msg err">Enter a name to preview.</div>';return}rm.innerHTML='';var t=$('rt').value,d=$('rd').value,tm=$('rtm').value,lot=$('rl').value;
rpv.innerHTML='<div class="panel" style="background:var(--surface);margin-top:16px"><p style="color:var(--faint);font-size:13px;margin:0 0 10px">Preview. Not saved yet.</p><h3 class="serif" style="margin-bottom:6px">'+esc(n)+'</h3><div class="row"><span>Arrangement</span><span>'+esc(t)+'</span></div>'+(t==='Lawn lot'?'<div class="row"><span>Lawn lot</span><span>'+esc(lot||'Not chosen yet')+'</span></div>':'')+'<div class="row"><span>Date</span><span>'+(d?fd(d):'Not set')+'</span></div><div class="row"><span>Time</span><span>'+(tm?ft(tm):'Not set')+'</span></div><p style="color:var(--soft);font-size:13px;margin:10px 0 0">Staff only. This is never shown to the public.</p></div>'};
fillNames();fillLots();rS();
var up=function(){$('s1').textContent=OB.length;$('s2').textContent=OB.reduce(function(a,o){return a+o.cond.filter(function(c){return c[2]==='Approved'}).length},0);$('s3').textContent=OB.reduce(function(a,o){return a+o.candles},0)};up();
var lq=document.getElementById('lq'),lsf=document.getElementById('lsf'),ltb=document.getElementById('ltb');
var rl=function(){var q=lq.value.trim().toLowerCase(),f=lsf.value,c={Published:0,Draft:0,Archived:0};OB.forEach(function(o){c[o.status]++});
document.getElementById('lsum').textContent=OB.length+' records: '+c.Published+' published, '+c.Draft+' draft, '+c.Archived+' archived';
var r=OB.filter(function(o){return(!q||o.name.toLowerCase().indexOf(q)>-1)&&(!f||o.status===f)&&inR('ob',o.died)});
ltb.innerHTML=r.length?r.map(function(o){return '<tr><td><b>'+esc(o.name)+'</b></td><td>'+fd(o.died)+'</td><td>'+(/^Cremation/.test(o.inter)?'Cremation':'Lawn lot')+'</td><td>'+o.photos.length+'</td><td><select data-id="'+o.id+'" aria-label="Status for '+esc(o.name)+'">'+['Published','Draft','Archived'].map(function(t){return '<option'+(t===o.status?' selected':'')+'>'+t+'</option>'}).join('')+'</select></td><td style="white-space:nowrap"><a class="btn sm ghost" href="#/memorial/'+o.id+'">View</a> <button class="btn sm ghost" type="button" data-act="edit" data-id="'+o.id+'">Edit</button> <button class="btn sm ghost" type="button" data-act="del" data-id="'+o.id+'">Delete</button></td></tr>'}).join(''):'<tr><td colspan="6" class="empty">No records match.</td></tr>'};
lq.oninput=rl;lsf.onchange=rl;
ltb.onchange=function(e){var t=e.target.closest('select');if(!t)return;var o2=OB.filter(function(x){return x.id==t.dataset.id})[0];o2.status=t.value;logAct('Changed status of '+o2.name+' to '+t.value);up()};rl();
var np=[],mo=document.getElementById('mo'),mt=document.getElementById('mt'),at=document.getElementById('at');
var fill=function(k){mo.innerHTML=OB.map(function(o){return '<option value="'+o.id+'">'+esc(o.name)+'</option>'}).join('');if(k)mo.value=k;cur();fillNames()};
var cur=function(){var o=OB.filter(function(x){return x.id==mo.value})[0];if(o)thumbs(mt,o.photos);return o};
mo.onchange=cur;fill();
document.getElementById('mp').onchange=function(){var i=this,o=cur();readImgs(i.files).then(function(a){a.forEach(function(u){o.photos.push(u)});thumbs(mt,o.photos);i.value=''})};
document.getElementById('ap').onchange=function(){var i=this;readImgs(i.files).then(function(a){np=np.concat(a);thumbs(at,np);i.value=''})};
var tabs=document.getElementById('tabs'),cdl=document.getElementById('cdl'),inl=document.getElementById('inl');
var showTab=function(n){tabs.querySelectorAll('.tab').forEach(function(b){b.classList.toggle('on',b.dataset.tab===n)});document.querySelectorAll('.tp').forEach(function(p){p.classList.toggle('on',p.dataset.t===n)})};
tabs.onclick=function(e){var b=e.target.closest('.tab');if(b)showTab(b.dataset.tab)};
document.getElementById('cards').onclick=function(e){var b=e.target.closest('[data-go]');if(b){showTab(b.dataset.go);window.scrollTo(0,0)}};
var logRow=function(a){return '<div class="row"><span>'+esc(a[2])+'</span><span style="color:var(--faint)">'+esc(a[1])+', '+esc(a[0])+'</span></div>'};
var rLog=function(){var la=ACT.filter(function(x){return inR('lg',x[3])});document.getElementById('alg').innerHTML=la.length?la.map(logRow).join(''):'<div class="empty">No activity in this date range.</div>';document.getElementById('ra').innerHTML=ACT.slice(0,5).map(logRow).join('')};
/* ---- Condolence moderation ---- */
$('mod').checked=MOD.on;
$('mod').onchange=function(){MOD.on=this.checked;logAct(MOD.on?'Turned on review before condolences appear':'Turned off review: new condolences post immediately');rLog()};
var rCond=function(){var f=$('cfs').value,rows=[],pend=0;
OB.forEach(function(o){o.cond.forEach(function(c,i){if(c[2]==='Pending')pend++;if(f&&c[2]!==f)return;if(!inR('cn',c[3]))return;var d=' data-o="'+o.id+'" data-i="'+i+'"';
rows.push('<div class="row" style="align-items:flex-start"><span style="max-width:34rem"><b>'+esc(c[0])+'</b> on '+esc(o.name)+' <span class="pill'+(c[2]==='Approved'?'':' warn')+'">'+esc(c[2])+'</span><br><span style="color:var(--soft)">'+esc(c[1])+'</span></span><span style="display:flex;gap:8px;flex-wrap:wrap">'
+(c[2]!=='Approved'?'<button class="btn sm" type="button" data-a="ok"'+d+'>Approve</button>':'')
+(c[2]==='Pending'?'<button class="btn sm ghost" type="button" data-a="no"'+d+'>Reject</button>':'')
+(c[2]==='Approved'?'<button class="btn sm ghost" type="button" data-a="no"'+d+'>Hide</button>':'')
+'<button class="btn sm ghost" type="button" data-a="rm"'+d+'>Remove</button></span></div>')})});
tabs.querySelector('[data-tab=cond]').textContent=pend?'Condolences ('+pend+' pending)':'Condolences';
cdl.innerHTML=rows.length?rows.join(''):'<div class="empty">'+(f||$('cn_f').value||$('cn_t').value?'No condolences match these filters.':'No condolences yet.')+'</div>'};
$('cfs').onchange=rCond;
cdl.onclick=function(e){var b=e.target.closest('button');if(!b)return;var o=OB.filter(function(x){return x.id==b.dataset.o})[0],c=o.cond[b.dataset.i],a=b.dataset.a;
if(a==='ok'){c[2]='Approved';logAct('Approved a condolence from '+c[0]+' on '+o.name)}
else if(a==='no'){c[2]='Rejected';logAct('Rejected a condolence from '+c[0]+' on '+o.name)}
else{if(!b.dataset.arm){b.dataset.arm='1';b.textContent='Confirm remove';setTimeout(function(){if(b.isConnected){b.dataset.arm='';b.textContent='Remove'}},4000);return}
logAct('Removed a condolence from '+c[0]+' on '+o.name);o.cond.splice(b.dataset.i,1)}
up()};
/* ---- Inquiries with service filter ---- */
$('ifs').innerHTML='<option value="">All services</option>'+SVC.map(function(s){return '<option>'+s+'</option>'}).join('');
var rInq=function(){var un=INQ.filter(function(q){return q.status==='Unread'}).length,fs=$('ifs').value,fst=$('ist').value;tabs.querySelector('[data-tab=inq]').textContent=un?'Inquiries ('+un+')':'Inquiries';
var r=INQ.filter(function(q){return(!fs||(q.service||'General question')===fs)&&(!fst||q.status===fst)&&inR('iq',q.date)});
inl.innerHTML=r.length?r.map(function(q){return '<div class="row" style="align-items:flex-start"><span style="max-width:34rem"><b>'+esc(q.subject)+'</b> <span class="pill">'+esc(q.service||'General question')+'</span><br>'+esc(q.name)+' ('+esc(q.email)+'), '+esc(q.at)+'<br><span style="color:var(--soft)">'+esc(q.msg)+'</span></span><span style="display:flex;gap:8px;align-items:center;flex-wrap:wrap"><select data-id="'+q.id+'" aria-label="Status of inquiry from '+esc(q.name)+'">'+['Unread','Read','Replied'].map(function(t){return '<option'+(t===q.status?' selected':'')+'>'+t+'</option>'}).join('')+'</select><a class="btn sm ghost" href="mailto:'+esc(q.email)+'?subject='+encodeURIComponent('Re: '+q.subject)+'">Reply by email</a></span></div>'}).join(''):'<div class="empty">'+(INQ.length?'No inquiries match these filters.':'No inquiries yet.')+'</div>'};
$('ifs').onchange=rInq;$('ist').onchange=rInq;
inl.onchange=function(e){var t=e.target.closest('select');if(!t)return;var q=INQ.filter(function(x){return x.id==t.dataset.id})[0];q.status=t.value;logAct('Marked inquiry from '+q.name+' as '+t.value);up()};
var gv=$;
gv('c_nm').value=SITE.name;gv('c_tg').value=SITE.tagline;gv('c_pl').value=SITE.place;gv('c_m').value=CONTENT.mission;gv('c_v').value=CONTENT.vision;gv('c_p').value=CONTENT.philosophy;gv('c_ph').value=CONTENT.phone;gv('c_ad').value=CONTENT.address;gv('c_hr').value=CONTENT.hours;
gv('svl').innerHTML=SERV.map(function(x,i){return '<div class="fr"><label for="sv'+i+'">'+esc(x[0])+'</label><textarea id="sv'+i+'">'+esc(x[1])+'</textarea></div>'}).join('');
gv('sf').onsubmit=function(e){e.preventDefault();SITE.name=gv('c_nm').value.trim()||SITE.name;SITE.tagline=gv('c_tg').value.trim();SITE.place=gv('c_pl').value.trim();CONTENT.mission=gv('c_m').value.trim();CONTENT.vision=gv('c_v').value.trim();CONTENT.philosophy=gv('c_p').value.trim();CONTENT.phone=gv('c_ph').value.trim();CONTENT.address=gv('c_ad').value.trim();CONTENT.hours=gv('c_hr').value.trim();SERV.forEach(function(x,i){x[1]=gv('sv'+i).value.trim()});logAct('Updated site content');applyBrand();up();gv('sm2').innerHTML='<div class="msg">Saved. The public pages now show your changes.</div>'};
var up0=up;up=function(){up0();rl();rLog();rCond();rInq()};
[['ob',rl],['sc',rS],['cn',rCond],['iq',rInq],['lg',rLog]].forEach(function(p){$(p[0]+'_f').onchange=$(p[0]+'_t').onchange=p[1];$(p[0]+'_x').onclick=function(){$(p[0]+'_f').value='';$(p[0]+'_t').value='';p[1]()}});
var af=document.getElementById('af'),am=document.getElementById('am'),apv=document.getElementById('apv'),aht=document.getElementById('aht'),editId=null;
var val=function(i){return document.getElementById(i).value.trim()};
var reset=function(){af.reset();np=[];thumbs(at,np);editId=null;aht.textContent='Add an obituary';apv.innerHTML=''};
var save=function(st){if(!af.reportValidity())return;var f={name:val('an'),born:val('ab'),died:val('ad'),bio:val('abio'),family:val('afm'),inter:val('ai')||'To be announced',photos:np.slice(),status:st},o,was=!!editId;
if(editId){o=OB.filter(function(x){return x.id==editId})[0];for(var k in f)o[k]=f[k]}else{f.id=OB.reduce(function(m,x){return Math.max(m,x.id)},0)+1;f.candles=0;f.sched=[];f.cond=[];o=f;OB.unshift(o)}
logAct((st==='Published'?'Published':'Saved as draft')+': '+o.name+(was?' (edited)':''));reset();am.innerHTML='<div class="msg">'+(st==='Published'?'Published':'Saved as a draft')+(was?' (changes saved)':'')+'. <a href="#/memorial/'+o.id+'" style="text-decoration:underline">'+(st==='Published'?'View the memorial page':'Preview the memorial page')+'</a></div>';fill(o.id);rl();up()};
document.getElementById('bpub').onclick=function(){save('Published')};
document.getElementById('bdr').onclick=function(){save('Draft')};
document.getElementById('bcx').onclick=function(){var had=editId||val('an')||val('abio')||np.length;reset();am.innerHTML=had?'<div class="msg">Cancelled. Nothing was saved.</div>':''};
document.getElementById('bpv').onclick=function(){var n=val('an');if(!n){am.innerHTML='<div class="msg err">Enter a name to preview.</div>';return}am.innerHTML='';var b=val('ab'),d=val('ad');apv.innerHTML='<div class="panel" style="background:var(--surface);margin-top:16px"><p style="color:var(--faint);font-size:13px;margin:0 0 10px">Preview. Not saved yet.</p><div style="display:flex;gap:14px;align-items:center;margin-bottom:10px"><div class="ph" style="width:64px;height:64px;font-size:22px;background:var(--pale);color:var(--sage);border-color:var(--line)">'+(np.length?'<img src="'+np[0]+'" alt="">':esc(ini(n)))+'</div><div><h3 class="serif">'+esc(n)+'</h3><span style="color:var(--faint);font-size:13px">'+(b?fd(b):'?')+' to '+(d?fd(d):'?')+'</span></div></div><p style="margin:0;color:var(--soft)">'+esc(val('abio')||'No biography yet.')+'</p></div>'};
af.onsubmit=function(e){e.preventDefault();save('Published')};up();
ltb.onclick=function(e){var b=e.target.closest('button[data-act]');if(!b)return;var o=OB.filter(function(x){return x.id==b.dataset.id})[0];
if(b.dataset.act==='edit'){editId=o.id;document.getElementById('an').value=o.name;document.getElementById('ab').value=o.born;document.getElementById('ad').value=o.died;document.getElementById('abio').value=o.bio;document.getElementById('afm').value=o.family||'';document.getElementById('ai').value=o.inter;np=o.photos.slice();thumbs(at,np);aht.textContent='Edit obituary: '+o.name;apv.innerHTML='';am.innerHTML='<div class="msg">Editing. Choose Publish or Save as draft to keep your changes, or Cancel to leave this record as it was.</div>';af.scrollIntoView()}
else if(b.dataset.act==='del'){if(b.dataset.arm){logAct('Deleted obituary: '+o.name);OB.splice(OB.indexOf(o),1);fill();rl();up()}else{b.dataset.arm='1';b.textContent='Confirm delete';setTimeout(function(){if(b.isConnected){b.dataset.arm='';b.textContent='Delete'}},4000)}}};
},
memorial:function(id){var o=getOb(id);if(!o)return;document.title=o.name+' | '+SITE.name;
var g=document.getElementById('gal');if(g){var lb=document.getElementById('lb');g.onclick=function(e){var t=e.target.closest('img');if(!t)return;lb.querySelector('img').src=t.src;lb.showModal()};lb.onclick=function(){lb.close()}}
var rc=function(){var ap=o.cond.filter(function(c){return c[2]==='Approved'});document.getElementById('cl').innerHTML=ap.length?ap.map(function(c){return '<div class="cond"><p>\u201C'+esc(c[1])+'\u201D</p><small>'+esc(c[0])+'</small></div>'}).join(''):'<p style="color:var(--faint);font-size:14px">Be the first to leave a condolence.</p>'};rc();
document.getElementById('cdnote').textContent=MOD.on?'Messages are reviewed by our staff before they appear on this page.':'';
var cc=function(){document.getElementById('cc').textContent=o.candles+' candles lit'};cc();
document.getElementById('cb').onclick=function(){var c=document.getElementById('cd');if(c.classList.contains('lit'))return;c.classList.add('lit');o.candles++;document.getElementById('cbt').textContent='Candle lit. Thank you';cc()};
document.getElementById('cdf').onsubmit=function(e){e.preventDefault();var n=document.getElementById('cdn').value.trim()||'Anonymous';o.cond.push([n,document.getElementById('cdt').value.trim(),MOD.on?'Pending':'Approved',iso()]);rc();e.target.reset();document.getElementById('cdm').innerHTML='<div class="msg">'+(MOD.on?'Thank you. Your message was received and will appear after our staff review it.':'Your condolence was posted.')+'</div>'};
var url=location.href,t=encodeURIComponent(url),tx=encodeURIComponent('In memory of '+o.name),L=[['Facebook','https://www.facebook.com/sharer/sharer.php?u='+t],['WhatsApp','https://wa.me/?text='+tx+'%20'+t],['X','https://twitter.com/intent/tweet?text='+tx+'&url='+t],['Email','mailto:?subject='+tx+'&body='+t]];
document.getElementById('sh').innerHTML=L.map(function(l){return '<a class="btn sm ghost" target="_blank" rel="noopener" href="'+l[1]+'">'+l[0]+'</a>'}).join('')+'<button class="btn sm ghost" id="cp" type="button">Copy link</button>';
document.getElementById('cp').onclick=function(){var b=this;try{navigator.clipboard.writeText(url).then(function(){b.textContent='Link copied'})}catch(x){b.textContent='Copy failed'}};
var q=document.getElementById('qr');q.innerHTML='';try{new QRCode(q,{text:url,width:160,height:160})}catch(x){q.textContent='QR code unavailable'}
document.getElementById('qd').onclick=function(){var sc=q.querySelector('canvas')||q.querySelector('img');if(!sc)return;
var W=420,H=560,c=document.createElement('canvas');c.width=W;c.height=H;var x=c.getContext('2d');
x.fillStyle='#fff';x.fillRect(0,0,W,H);x.strokeStyle='#A8854F';x.lineWidth=2;x.strokeRect(12,12,W-24,H-24);x.lineWidth=1;x.strokeRect(20,20,W-40,H-40);
x.imageSmoothingEnabled=false;x.drawImage(sc,(W-280)/2,48,280,280);
x.save();x.translate(W/2-22,346);x.scale(1.3,1.3);x.fillStyle='#A8854F';x.fill(new Path2D('M17 2c5 5 7.5 8.5 5 12.5-1.2 2-8.8 2-10 0C9.5 10.5 12 7 17 2z'));x.fillStyle='#fff';x.fill(new Path2D('M17 8c2 2.5 2.5 4 1.5 5.500-.6.900-2.400.900-3 0C14.500 12 15 10.500 17 8z'));x.lineCap='round';x.strokeStyle='#26222B';x.lineWidth=1.6;x.stroke(new Path2D('M17 16v4'));x.strokeStyle='#6B5B7B';x.lineWidth=1.8;x.stroke(new Path2D('M11 20h12a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H11a2 2 0 0 1-2-2V22a2 2 0 0 1 2-2z'));x.stroke(new Path2D('M5 37h24'));x.restore();
x.textAlign='center';x.fillStyle='#26222B';x.font='500 24px Georgia,serif';x.fillText(SITE.name,W/2,432,W-70);x.fillStyle='#6E6877';x.font='14px Arial,sans-serif';x.fillText(SITE.tagline+' \u00b7 '+SITE.place,W/2,456,W-70);
x.strokeStyle='#DAD3DF';x.lineWidth=1;x.beginPath();x.moveTo(60,476);x.lineTo(W-60,476);x.stroke();x.fillStyle='#5A5461';x.font='italic 15px Georgia,serif';x.fillText('In loving memory of '+o.name,W/2,506,W-80);
var a=document.createElement('a');a.href=c.toDataURL('image/png');a.download='obituary-'+o.id+'-qr.png';a.click()}}
};
/* ---- router ---- */
function route(){var p=(location.hash||'#/').slice(2).split('/'),r=p[0]||'home',a=p[1],toContact=false;if(r==='contact'){r='home';toContact=true}if(!pages[r]){r='home'}
document.getElementById('app').innerHTML=pages[r](a);if(after[r])after[r](a);
document.querySelectorAll('#nav a').forEach(function(x){x.classList.toggle('cur',toContact?x.dataset.r==='contact':(x.dataset.r===r)||(r==='memorial'&&x.dataset.r==='obituaries'))});
var fp=document.getElementById('fph');if(fp)fp.textContent=CONTENT.phone;applyBrand();var al=document.getElementById('authlink');al.textContent=session?'Dashboard':'Staff sign in';al.href=session?'#/admin':'#/login';
if(r!=='memorial')document.title=SITE.name;if(toContact){var c=document.getElementById('contact-home');if(c)c.scrollIntoView()}else if(r==='services'&&a&&document.getElementById(a)){document.getElementById(a).scrollIntoView()}else window.scrollTo(0,0)}
window.addEventListener('hashchange',route);route();
